environment:

  matrix:
    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      CONDA_NPY: "18"

install:
  - git submodule update --init --recursive
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\ci\\appveyor\\install.ps1
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - conda install -y coverage nose mock
  - conda install -y ipython numpy pandas SQLAlchemy pytables
  - python setup.py install

build: false

test_script:
  - python setup.py test
