language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
addons:
    apt:
        packages:
            - python-virtualenv
            - libhdf5-serial-dev
sudo: false
before_install:
    - pip install codecov
    - pip install coveralls
install: ./build_venv.sh
cache:
    directories:
    - venv
script: . load_env; python setup.py nosetests -a '!performance' --cover-erase --with-coverage --cover-package=phildb --cover-html --with-xunit; coverage xml --rcfile=.coveragerc
after_success:
    - codecov
    - coveralls
