language: python
python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_install:
    - sudo apt-get install python-virtualenv libhdf5-serial-dev
install: ./build_venv.sh
cache:
    directories:
    - venv
script: . load_env; nosetests -a '!performance'
